# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HTR United Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install htr-united-metadata-generator
    - name: Run Report
      run: |
        humGenerator --group --parse page data/*/*.xml --github-envs
        cat envs.txt >> $GITHUB_ENV
    - name: Create Characters Badge
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "94e2fc8cbb4a71eeacfbb46672d6ff7f"
        filename: "chars.json" # Eg. cremma-print-badges-chars.json
        label: "Characters" # Any message you want
        message: ${{ env.HTRUNITED_CHARS }} # or env.HTRUNITED_LINES or env.HTRUNITED_REGNS
        color: informational # You can change the style and colors
        style: "flat-square"
    - name: Create Lines Badge
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "94e2fc8cbb4a71eeacfbb46672d6ff7f"
        filename: "lines.json" # Eg. cremma-print-badges-chars.json
        label: "Lines" # Any message you want
        message: ${{ env.HTRUNITED_LINES }} # or env.HTRUNITED_LINES or env.HTRUNITED_REGNS
        color: informational 
        style: "flat-square"
    - name: Create Region Badge
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "94e2fc8cbb4a71eeacfbb46672d6ff7f"
        filename: "regions.json" 
        label: "Regions" 
        message: ${{ env.HTRUNITED_REGNS }} 
        color: informational # You can change the style and colors
        style: "flat-square"
